(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Zee Model",
  Authors -> {"Yang Ma"},
  Version -> "1.0.0",
  Date -> "04. 09. 2019",
  Institutions -> {"University of Pittsburgh"},
  Emails -> {"mayangluon@pitt.edu"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {ZEE, 0}};

FR$GoldstoneList={S[6], S[7]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HL",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHL,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HH",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHH,
    Indices -> {} },

S[3] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HA",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHA,
    Indices -> {} },

S[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "HpHm",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHpH,
    Indices -> {} },

S[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "Hpm",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHp,
    Indices -> {} },

S[6] == {
    SelfConjugate -> True,
    PropagatorLabel -> "G0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = 1;
GaugeXi[ S[3] ] = 1;
GaugeXi[ S[4] ] = 1;
GaugeXi[ S[5] ] = 1;
GaugeXi[ S[6] ] = GaugeXi[Z];
GaugeXi[ S[7] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MHL[ ___ ] := MHL;
MHH[ ___ ] := MHH;
MHA[ ___ ] := MHA;
MHpH[ ___ ] := MHpH;
MHp[ ___ ] := MHp;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc1*SUNF[e1x2, e2x2, e3x2]), 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc3, 0}, {I*gc3, 0}, {I*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {I*gc3, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc4, 0}, {(-I)*gc4, 0}, {(2*I)*gc4, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc5, 0}, {I*gc5, 0}, {I*gc5, 0}, {(-I)*gc5, 0}, {(-I)*gc5, 0}, {I*gc5, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc6, 0}, {(-I)*gc6, 0}, {(2*I)*gc6, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc7, 0}, {I*gc7, 0}, {I*gc7, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc8, 0}, {(-I)*gc8, 0}, {(2*I)*gc8, 0}},

C[ S[6] , S[6] , S[6] , S[6] ] == {{(-3*I)*lam1, 0}},

C[ S[6] , S[6] , S[7] , -S[7] ] == {{(-I)*lam1, 0}},

C[ S[7] , S[7] , -S[7] , -S[7] ] == {{(-2*I)*lam1, 0}},

C[ S[6] , S[6] , S[1] , S[1] ] == {{(-I)*(cab^2*lam1 + 2*cab*lam6*sab + (lam3 + lam4 - lam5)*sab^2), 0}},

C[ S[7] , -S[7] , S[1] , S[1] ] == {{(-I)*(cab^2*lam1 + 2*cab*lam6*sab + lam3*sab^2), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-3*I)*(cab^4*lam1 + 4*cab^3*lam6*sab + 2*cab^2*(lam3 + lam4 + lam5)*sab^2 + 4*cab*lam7*sab^3 + lam2*sab^4), 0}},

C[ S[6] , S[3] , S[5] , -S[5] ] == {{(-I)*(cphi^2*lam10 + lam7*sphi^2), 0}},

C[ S[2] , S[1] , S[5] , -S[5] ] == {{(-I)*(cab*sab*(cphi^2*(-lam8 + lam9) + (lam2 - lam3)*sphi^2) + cab^2*(cphi^2*lam10 + lam7*sphi^2) - sab^2*(cphi^2*lam10 + lam7*sphi^2)), 0}},

C[ -S[7] , S[5] , -S[5] , S[4] ] == {{(-I)*cphi*(cphi^2*lam10 - (lam10 - 2*lam7)*sphi^2), 0}},

C[ S[7] , S[5] , -S[5] , -S[4] ] == {{(-I)*cphi*(cphi^2*lam10 - (lam10 - 2*lam7)*sphi^2), 0}},

C[ S[3] , S[3] , S[3] , S[3] ] == {{(-3*I)*lam2, 0}},

C[ S[3] , S[3] , S[2] , S[2] ] == {{(-I)*(cab^2*lam2 - 2*cab*lam7*sab + (lam3 + lam4 - lam5)*sab^2), 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-3*I)*(cab^4*lam2 - 4*cab^3*lam7*sab + 2*cab^2*(lam3 + lam4 + lam5)*sab^2 - 4*cab*lam6*sab^3 + lam1*sab^4), 0}},

C[ S[3] , S[3] , S[4] , -S[4] ] == {{(-I)*(cphi^2*lam2 + lam9*sphi^2), 0}},

C[ S[2] , S[2] , S[4] , -S[4] ] == {{(-I)*(-2*cab*sab*(cphi^2*lam7 + lam10*sphi^2) + sab^2*(cphi^2*lam3 + lam8*sphi^2) + cab^2*(cphi^2*lam2 + lam9*sphi^2)), 0}},

C[ S[4] , S[4] , -S[4] , -S[4] ] == {{(-2*I)*(cphi^4*lam2 + 2*cphi^2*lam9*sphi^2 + 2*lameta*sphi^4), 0}},

C[ S[6] , S[6] , S[3] , S[3] ] == {{(-I)*(lam3 + lam4 + lam5), 0}},

C[ S[7] , -S[7] , S[3] , S[3] ] == {{(-I)*lam3, 0}},

C[ S[6] , S[6] , S[2] , S[2] ] == {{(-I)*(cab^2*(lam3 + lam4 - lam5) - 2*cab*lam6*sab + lam1*sab^2), 0}},

C[ S[7] , -S[7] , S[2] , S[2] ] == {{(-I)*(cab^2*lam3 - 2*cab*lam6*sab + lam1*sab^2), 0}},

C[ S[3] , S[3] , S[1] , S[1] ] == {{(-I)*(cab^2*(lam3 + lam4 - lam5) + 2*cab*lam7*sab + lam2*sab^2), 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-I)*(cab^4*(lam3 + lam4 + lam5) + 6*cab^3*(-lam6 + lam7)*sab + cab^2*(3*lam1 + 3*lam2 - 4*(lam3 + lam4 + lam5))*sab^2 + 6*cab*(lam6 - lam7)*sab^3 + (lam3 + lam4 + lam5)*sab^4), 0}},

C[ S[6] , S[6] , S[4] , -S[4] ] == {{(-I)*(cphi^2*lam3 + lam8*sphi^2), 0}},

C[ S[7] , -S[7] , S[4] , -S[4] ] == {{(-I)*(cphi^2*(lam3 + lam4) + lam8*sphi^2), 0}},

C[ S[1] , S[1] , S[4] , -S[4] ] == {{(-I)*(2*cab*sab*(cphi^2*lam7 + lam10*sphi^2) + cab^2*(cphi^2*lam3 + lam8*sphi^2) + sab^2*(cphi^2*lam2 + lam9*sphi^2)), 0}},

C[ S[6] , -S[7] , S[3] , S[4] ] == {{(-I/2)*cphi*(lam4 + lam5), 0}},

C[ S[6] , -S[7] , S[2] , S[4] ] == {{(cab*cphi*(lam4 - lam5))/2, 0}},

C[ -S[7] , S[3] , S[1] , S[4] ] == {{-(cab*cphi*(lam4 - lam5))/2, 0}},

C[ -S[7] , S[2] , S[1] , S[4] ] == {{(-I/2)*cphi*(cab^2*(lam4 + lam5) + 2*cab*(-lam6 + lam7)*sab - (lam4 + lam5)*sab^2), 0}},

C[ S[6] , S[7] , S[3] , -S[4] ] == {{(-I/2)*cphi*(lam4 + lam5), 0}},

C[ S[6] , S[7] , S[2] , -S[4] ] == {{-(cab*cphi*(lam4 - lam5))/2, 0}},

C[ S[7] , S[3] , S[1] , -S[4] ] == {{(cab*cphi*(lam4 - lam5))/2, 0}},

C[ S[7] , S[2] , S[1] , -S[4] ] == {{(-I/2)*cphi*(cab^2*(lam4 + lam5) + 2*cab*(-lam6 + lam7)*sab - (lam4 + lam5)*sab^2), 0}},

C[ S[6] , S[3] , S[2] , S[1] ] == {{(-I)*(cab^2*lam5 + cab*(-lam6 + lam7)*sab - lam5*sab^2), 0}},

C[ -S[7] , -S[7] , S[4] , S[4] ] == {{(-2*I)*cphi^2*lam5, 0}},

C[ S[7] , S[7] , -S[4] , -S[4] ] == {{(-2*I)*cphi^2*lam5, 0}},

C[ S[6] , S[6] , S[6] , S[3] ] == {{(-3*I)*lam6, 0}},

C[ S[6] , S[7] , -S[7] , S[3] ] == {{(-I)*lam6, 0}},

C[ S[6] , S[6] , S[2] , S[1] ] == {{(-I)*(cab^2*lam6 + cab*(-lam1 + lam3 + lam4 - lam5)*sab - lam6*sab^2), 0}},

C[ S[7] , -S[7] , S[2] , S[1] ] == {{(-I)*(cab^2*lam6 + cab*(-lam1 + lam3)*sab - lam6*sab^2), 0}},

C[ S[6] , S[3] , S[1] , S[1] ] == {{(-I)*(cab^2*lam6 + 2*cab*lam5*sab + lam7*sab^2), 0}},

C[ S[2] , S[1] , S[1] , S[1] ] == {{(-3*I)*(cab^4*lam6 + cab^3*(-lam1 + lam3 + lam4 + lam5)*sab + 3*cab^2*(-lam6 + lam7)*sab^2 + cab*(lam2 - lam3 - lam4 - lam5)*sab^3 - lam7*sab^4), 0}},

C[ S[6] , S[6] , -S[7] , S[4] ] == {{(-I)*cphi*lam6, 0}},

C[ S[7] , -S[7] , -S[7] , S[4] ] == {{(-2*I)*cphi*lam6, 0}},

C[ -S[7] , S[1] , S[1] , S[4] ] == {{(-I)*cphi*(cab^2*lam6 + cab*(lam4 + lam5)*sab + lam7*sab^2), 0}},

C[ S[6] , S[6] , S[7] , -S[4] ] == {{(-I)*cphi*lam6, 0}},

C[ S[7] , S[7] , -S[7] , -S[4] ] == {{(-2*I)*cphi*lam6, 0}},

C[ S[7] , S[1] , S[1] , -S[4] ] == {{(-I)*cphi*(cab^2*lam6 + cab*(lam4 + lam5)*sab + lam7*sab^2), 0}},

C[ S[6] , S[3] , S[3] , S[3] ] == {{(-3*I)*lam7, 0}},

C[ S[6] , S[3] , S[2] , S[2] ] == {{(-I)*(cab^2*lam7 - 2*cab*lam5*sab + lam6*sab^2), 0}},

C[ S[3] , S[3] , S[2] , S[1] ] == {{(-I)*(cab^2*lam7 + cab*(lam2 - lam3 - lam4 + lam5)*sab - lam7*sab^2), 0}},

C[ S[2] , S[2] , S[2] , S[1] ] == {{(-3*I)*(cab^4*lam7 + cab^3*(lam2 - lam3 - lam4 - lam5)*sab + 3*cab^2*(lam6 - lam7)*sab^2 + cab*(-lam1 + lam3 + lam4 + lam5)*sab^3 - lam6*sab^4), 0}},

C[ -S[7] , S[3] , S[3] , S[4] ] == {{(-I)*cphi*lam7, 0}},

C[ -S[7] , S[2] , S[2] , S[4] ] == {{(-I)*cphi*(cab^2*lam7 - cab*(lam4 + lam5)*sab + lam6*sab^2), 0}},

C[ S[7] , S[3] , S[3] , -S[4] ] == {{(-I)*cphi*lam7, 0}},

C[ S[7] , S[2] , S[2] , -S[4] ] == {{(-I)*cphi*(cab^2*lam7 - cab*(lam4 + lam5)*sab + lam6*sab^2), 0}},

C[ S[6] , S[3] , S[4] , -S[4] ] == {{(-I)*(cphi^2*lam7 + lam10*sphi^2), 0}},

C[ S[2] , S[1] , S[4] , -S[4] ] == {{(-I)*(cab^2*(cphi^2*lam7 + lam10*sphi^2) - sab^2*(cphi^2*lam7 + lam10*sphi^2) + cab*sab*(cphi^2*(lam2 - lam3) + (-lam8 + lam9)*sphi^2)), 0}},

C[ -S[7] , S[4] , S[4] , -S[4] ] == {{(-2*I)*cphi*(cphi^2*lam7 + lam10*sphi^2), 0}},

C[ S[7] , S[4] , -S[4] , -S[4] ] == {{(-2*I)*cphi*(cphi^2*lam7 + lam10*sphi^2), 0}},

C[ S[6] , S[6] , S[5] , -S[5] ] == {{(-I)*(cphi^2*lam8 + lam3*sphi^2), 0}},

C[ S[7] , -S[7] , S[5] , -S[5] ] == {{(-I)*(cphi^2*lam8 + (lam3 + lam4)*sphi^2), 0}},

C[ S[1] , S[1] , S[5] , -S[5] ] == {{(-I)*(sab^2*(cphi^2*lam9 + lam2*sphi^2) + cab^2*(cphi^2*lam8 + lam3*sphi^2) + 2*cab*sab*(cphi^2*lam10 + lam7*sphi^2)), 0}},

C[ S[3] , S[3] , S[5] , -S[5] ] == {{(-I)*(cphi^2*lam9 + lam2*sphi^2), 0}},

C[ S[2] , S[2] , S[5] , -S[5] ] == {{(-I)*(cab^2*(cphi^2*lam9 + lam2*sphi^2) + sab^2*(cphi^2*lam8 + lam3*sphi^2) - 2*cab*sab*(cphi^2*lam10 + lam7*sphi^2)), 0}},

C[ S[5] , -S[5] , S[4] , -S[4] ] == {{(-I)*(cphi^4*lam9 + 2*cphi^2*(lam2 - lam9 + 2*lameta)*sphi^2 + lam9*sphi^4), 0}},

C[ S[5] , S[5] , -S[5] , -S[5] ] == {{(-2*I)*(2*cphi^4*lameta + 2*cphi^2*lam9*sphi^2 + lam2*sphi^4), 0}},

C[ -S[7] , S[3] , S[5] ] == {{(-(Sqrt[2]*cphi*muzee) + (-lam4 + lam5)*sphi*vev)/2, 0}},

C[ -S[7] , S[2] , S[5] ] == {{(-I/2)*(Sqrt[2]*cab*cphi*muzee + cab*(lam4 + lam5)*sphi*vev - 2*lam6*sab*sphi*vev), 0}},

C[ S[7] , S[3] , -S[5] ] == {{(Sqrt[2]*cphi*muzee + (lam4 - lam5)*sphi*vev)/2, 0}},

C[ S[7] , S[2] , -S[5] ] == {{(-I/2)*(Sqrt[2]*cab*cphi*muzee + cab*(lam4 + lam5)*sphi*vev - 2*lam6*sab*sphi*vev), 0}},

C[ S[6] , -S[5] , S[4] ] == {{-((muzee*(cphi^2 + sphi^2))/Sqrt[2]), 0}},

C[ S[1] , -S[5] , S[4] ] == {{(I/2)*(2*cphi*(lam10 - lam7)*sab*sphi*vev + cab*(Sqrt[2]*cphi^2*muzee - Sqrt[2]*muzee*sphi^2 + 2*cphi*(-lam3 + lam8)*sphi*vev)), 0}},

C[ S[6] , S[5] , -S[4] ] == {{(muzee*(cphi^2 + sphi^2))/Sqrt[2], 0}},

C[ S[1] , S[5] , -S[4] ] == {{(I/2)*(2*cphi*(lam10 - lam7)*sab*sphi*vev + cab*(Sqrt[2]*cphi^2*muzee - Sqrt[2]*muzee*sphi^2 + 2*cphi*(-lam3 + lam8)*sphi*vev)), 0}},

C[ -S[7] , S[3] , S[2] , S[4] ] == {{(cphi*(lam4 - lam5)*sab)/2, 0}},

C[ S[6] , -S[7] , S[1] , S[4] ] == {{(cphi*(lam4 - lam5)*sab)/2, 0}},

C[ S[7] , S[3] , S[2] , -S[4] ] == {{-(cphi*(lam4 - lam5)*sab)/2, 0}},

C[ S[6] , S[7] , S[1] , -S[4] ] == {{-(cphi*(lam4 - lam5)*sab)/2, 0}},

C[ -S[7] , S[1] , S[5] ] == {{(-I/2)*(Sqrt[2]*cphi*muzee*sab + (2*cab*lam6 + (lam4 + lam5)*sab)*sphi*vev), 0}},

C[ S[7] , S[1] , -S[5] ] == {{(-I/2)*(Sqrt[2]*cphi*muzee*sab + (2*cab*lam6 + (lam4 + lam5)*sab)*sphi*vev), 0}},

C[ S[2] , -S[5] , S[4] ] == {{(-I/2)*(Sqrt[2]*cphi^2*muzee*sab - Sqrt[2]*muzee*sab*sphi^2 - 2*cphi*(cab*(lam10 - lam7) + (lam3 - lam8)*sab)*sphi*vev), 0}},

C[ S[2] , S[5] , -S[4] ] == {{(-I/2)*(Sqrt[2]*cphi^2*muzee*sab - Sqrt[2]*muzee*sab*sphi^2 - 2*cphi*(cab*(lam10 - lam7) + (lam3 - lam8)*sab)*sphi*vev), 0}},

C[ -S[7] , S[5] , S[5] , -S[5] ] == {{(-2*I)*sphi*(cphi^2*lam10 + lam7*sphi^2), 0}},

C[ S[7] , S[5] , -S[5] , -S[5] ] == {{(-2*I)*sphi*(cphi^2*lam10 + lam7*sphi^2), 0}},

C[ S[6] , S[3] , -S[5] , S[4] ] == {{I*cphi*(lam10 - lam7)*sphi, 0}},

C[ S[2] , S[1] , -S[5] , S[4] ] == {{I*cphi*(cab^2*(lam10 - lam7) + cab*(-lam2 + lam3 - lam8 + lam9)*sab + (-lam10 + lam7)*sab^2)*sphi, 0}},

C[ -S[7] , -S[5] , S[4] , S[4] ] == {{(2*I)*cphi^2*(lam10 - lam7)*sphi, 0}},

C[ S[6] , S[3] , S[5] , -S[4] ] == {{I*cphi*(lam10 - lam7)*sphi, 0}},

C[ S[2] , S[1] , S[5] , -S[4] ] == {{I*cphi*(cab^2*(lam10 - lam7) + cab*(-lam2 + lam3 - lam8 + lam9)*sab + (-lam10 + lam7)*sab^2)*sphi, 0}},

C[ -S[7] , S[5] , S[4] , -S[4] ] == {{(-I)*sphi*(-(cphi^2*(lam10 - 2*lam7)) + lam10*sphi^2), 0}},

C[ S[7] , -S[5] , S[4] , -S[4] ] == {{(-I)*sphi*(-(cphi^2*(lam10 - 2*lam7)) + lam10*sphi^2), 0}},

C[ S[7] , S[5] , -S[4] , -S[4] ] == {{(2*I)*cphi^2*(lam10 - lam7)*sphi, 0}},

C[ S[3] , S[3] , -S[5] , S[4] ] == {{(-I)*cphi*(lam2 - lam9)*sphi, 0}},

C[ S[2] , S[2] , -S[5] , S[4] ] == {{(-I)*cphi*(cab^2*(lam2 - lam9) + 2*cab*(lam10 - lam7)*sab + (lam3 - lam8)*sab^2)*sphi, 0}},

C[ S[3] , S[3] , S[5] , -S[4] ] == {{(-I)*cphi*(lam2 - lam9)*sphi, 0}},

C[ S[2] , S[2] , S[5] , -S[4] ] == {{(-I)*cphi*(cab^2*(lam2 - lam9) + 2*cab*(lam10 - lam7)*sab + (lam3 - lam8)*sab^2)*sphi, 0}},

C[ -S[5] , S[4] , S[4] , -S[4] ] == {{(-2*I)*cphi*sphi*(cphi^2*(lam2 - lam9) + (lam9 - 2*lameta)*sphi^2), 0}},

C[ S[5] , S[4] , -S[4] , -S[4] ] == {{(-2*I)*cphi*sphi*(cphi^2*(lam2 - lam9) + (lam9 - 2*lameta)*sphi^2), 0}},

C[ S[6] , S[6] , -S[5] , S[4] ] == {{(-I)*cphi*(lam3 - lam8)*sphi, 0}},

C[ S[7] , -S[7] , -S[5] , S[4] ] == {{(-I)*cphi*(lam3 + lam4 - lam8)*sphi, 0}},

C[ S[1] , S[1] , -S[5] , S[4] ] == {{(-I)*cphi*(cab^2*(lam3 - lam8) + 2*cab*(-lam10 + lam7)*sab + (lam2 - lam9)*sab^2)*sphi, 0}},

C[ S[6] , S[6] , S[5] , -S[4] ] == {{(-I)*cphi*(lam3 - lam8)*sphi, 0}},

C[ S[7] , -S[7] , S[5] , -S[4] ] == {{(-I)*cphi*(lam3 + lam4 - lam8)*sphi, 0}},

C[ S[1] , S[1] , S[5] , -S[4] ] == {{(-I)*cphi*(cab^2*(lam3 - lam8) + 2*cab*(-lam10 + lam7)*sab + (lam2 - lam9)*sab^2)*sphi, 0}},

C[ S[6] , -S[7] , S[3] , S[5] ] == {{(-I/2)*(lam4 + lam5)*sphi, 0}},

C[ S[6] , -S[7] , S[2] , S[5] ] == {{(cab*(lam4 - lam5)*sphi)/2, 0}},

C[ -S[7] , S[3] , S[1] , S[5] ] == {{-(cab*(lam4 - lam5)*sphi)/2, 0}},

C[ -S[7] , S[2] , S[1] , S[5] ] == {{(-I/2)*(cab^2*(lam4 + lam5) + 2*cab*(-lam6 + lam7)*sab - (lam4 + lam5)*sab^2)*sphi, 0}},

C[ S[6] , S[7] , S[3] , -S[5] ] == {{(-I/2)*(lam4 + lam5)*sphi, 0}},

C[ S[6] , S[7] , S[2] , -S[5] ] == {{-(cab*(lam4 - lam5)*sphi)/2, 0}},

C[ S[7] , S[3] , S[1] , -S[5] ] == {{(cab*(lam4 - lam5)*sphi)/2, 0}},

C[ S[7] , S[2] , S[1] , -S[5] ] == {{(-I/2)*(cab^2*(lam4 + lam5) + 2*cab*(-lam6 + lam7)*sab - (lam4 + lam5)*sab^2)*sphi, 0}},

C[ -S[7] , -S[7] , S[5] , S[4] ] == {{(-2*I)*cphi*lam5*sphi, 0}},

C[ S[7] , S[7] , -S[5] , -S[4] ] == {{(-2*I)*cphi*lam5*sphi, 0}},

C[ S[6] , S[6] , -S[7] , S[5] ] == {{(-I)*lam6*sphi, 0}},

C[ S[7] , -S[7] , -S[7] , S[5] ] == {{(-2*I)*lam6*sphi, 0}},

C[ -S[7] , S[1] , S[1] , S[5] ] == {{(-I)*(cab^2*lam6 + cab*(lam4 + lam5)*sab + lam7*sab^2)*sphi, 0}},

C[ S[6] , S[6] , S[7] , -S[5] ] == {{(-I)*lam6*sphi, 0}},

C[ S[7] , S[7] , -S[7] , -S[5] ] == {{(-2*I)*lam6*sphi, 0}},

C[ S[7] , S[1] , S[1] , -S[5] ] == {{(-I)*(cab^2*lam6 + cab*(lam4 + lam5)*sab + lam7*sab^2)*sphi, 0}},

C[ -S[7] , S[3] , S[3] , S[5] ] == {{(-I)*lam7*sphi, 0}},

C[ -S[7] , S[2] , S[2] , S[5] ] == {{(-I)*(cab^2*lam7 - cab*(lam4 + lam5)*sab + lam6*sab^2)*sphi, 0}},

C[ S[7] , S[3] , S[3] , -S[5] ] == {{(-I)*lam7*sphi, 0}},

C[ S[7] , S[2] , S[2] , -S[5] ] == {{(-I)*(cab^2*lam7 - cab*(lam4 + lam5)*sab + lam6*sab^2)*sphi, 0}},

C[ S[5] , -S[5] , -S[5] , S[4] ] == {{(-2*I)*cphi*sphi*(cphi^2*(lam9 - 2*lameta) + (lam2 - lam9)*sphi^2), 0}},

C[ S[5] , S[5] , -S[5] , -S[4] ] == {{(-2*I)*cphi*sphi*(cphi^2*(lam9 - 2*lameta) + (lam2 - lam9)*sphi^2), 0}},

C[ S[1] , S[5] , -S[5] ] == {{(-I)*(sab*(cphi^2*lam10 + lam7*sphi^2)*vev + cab*(-(Sqrt[2]*cphi*muzee*sphi) + cphi^2*lam8*vev + lam3*sphi^2*vev)), 0}},

C[ -S[7] , S[3] , S[4] ] == {{(Sqrt[2]*muzee*sphi + cphi*(-lam4 + lam5)*vev)/2, 0}},

C[ -S[7] , S[2] , S[4] ] == {{(I/2)*(Sqrt[2]*cab*muzee*sphi - cab*cphi*(lam4 + lam5)*vev + 2*cphi*lam6*sab*vev), 0}},

C[ S[7] , S[3] , -S[4] ] == {{(-(Sqrt[2]*muzee*sphi) + cphi*(lam4 - lam5)*vev)/2, 0}},

C[ S[7] , S[2] , -S[4] ] == {{(I/2)*(Sqrt[2]*cab*muzee*sphi - cab*cphi*(lam4 + lam5)*vev + 2*cphi*lam6*sab*vev), 0}},

C[ S[1] , S[4] , -S[4] ] == {{(-I)*(sab*(cphi^2*lam7 + lam10*sphi^2)*vev + cab*(Sqrt[2]*cphi*muzee*sphi + cphi^2*lam3*vev + lam8*sphi^2*vev)), 0}},

C[ -S[7] , S[3] , S[2] , S[5] ] == {{((lam4 - lam5)*sab*sphi)/2, 0}},

C[ S[6] , -S[7] , S[1] , S[5] ] == {{((lam4 - lam5)*sab*sphi)/2, 0}},

C[ S[7] , S[3] , S[2] , -S[5] ] == {{-((lam4 - lam5)*sab*sphi)/2, 0}},

C[ S[6] , S[7] , S[1] , -S[5] ] == {{-((lam4 - lam5)*sab*sphi)/2, 0}},

C[ S[2] , S[5] , -S[5] ] == {{(-I)*(Sqrt[2]*cphi*muzee*sab*sphi + cphi^2*(cab*lam10 - lam8*sab)*vev + (cab*lam7 - lam3*sab)*sphi^2*vev), 0}},

C[ -S[7] , S[1] , S[4] ] == {{(I/2)*(Sqrt[2]*muzee*sab*sphi - cphi*(2*cab*lam6 + (lam4 + lam5)*sab)*vev), 0}},

C[ S[7] , S[1] , -S[4] ] == {{(I/2)*(Sqrt[2]*muzee*sab*sphi - cphi*(2*cab*lam6 + (lam4 + lam5)*sab)*vev), 0}},

C[ S[2] , S[4] , -S[4] ] == {{I*(Sqrt[2]*cphi*muzee*sab*sphi + (-(cab*lam10) + lam8*sab)*sphi^2*vev + cphi^2*(-(cab*lam7*vev) + lam3*sab*vev)), 0}},

C[ S[7] , -S[5] , -S[5] , S[4] ] == {{(2*I)*cphi*(lam10 - lam7)*sphi^2, 0}},

C[ -S[7] , S[5] , S[5] , -S[4] ] == {{(2*I)*cphi*(lam10 - lam7)*sphi^2, 0}},

C[ -S[5] , -S[5] , S[4] , S[4] ] == {{(-2*I)*cphi^2*(lam2 - 2*lam9 + 2*lameta)*sphi^2, 0}},

C[ S[5] , S[5] , -S[4] , -S[4] ] == {{(-2*I)*cphi^2*(lam2 - 2*lam9 + 2*lameta)*sphi^2, 0}},

C[ -S[7] , -S[7] , S[5] , S[5] ] == {{(-2*I)*lam5*sphi^2, 0}},

C[ S[7] , S[7] , -S[5] , -S[5] ] == {{(-2*I)*lam5*sphi^2, 0}},

C[ S[6] , S[6] , S[1] ] == {{(-I)*(cab*lam1 + lam6*sab)*vev, 0}},

C[ S[7] , -S[7] , S[1] ] == {{(-I)*(cab*lam1 + lam6*sab)*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-3*I)*(cab^3*lam1 + 3*cab^2*lam6*sab + cab*(lam3 + lam4 + lam5)*sab^2 + lam7*sab^3)*vev, 0}},

C[ S[3] , S[3] , S[1] ] == {{(-I)*(cab*(lam3 + lam4 - lam5) + lam7*sab)*vev, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-I)*(cab^3*(lam3 + lam4 + lam5) + 3*cab^2*(-2*lam6 + lam7)*sab + cab*(3*lam1 - 2*(lam3 + lam4 + lam5))*sab^2 + 3*lam6*sab^3)*vev, 0}},

C[ S[6] , S[3] , S[2] ] == {{(-I)*(cab*lam5 - lam6*sab)*vev, 0}},

C[ S[6] , S[6] , S[2] ] == {{(-I)*(cab*lam6 - lam1*sab)*vev, 0}},

C[ S[7] , -S[7] , S[2] ] == {{(-I)*(cab*lam6 - lam1*sab)*vev, 0}},

C[ S[6] , S[3] , S[1] ] == {{(-I)*(cab*lam6 + lam5*sab)*vev, 0}},

C[ S[2] , S[1] , S[1] ] == {{(-I)*(3*cab^3*lam6 + cab^2*(-3*lam1 + 2*(lam3 + lam4 + lam5))*sab + 3*cab*(-2*lam6 + lam7)*sab^2 - (lam3 + lam4 + lam5)*sab^3)*vev, 0}},

C[ S[3] , S[3] , S[2] ] == {{(-I)*(cab*lam7 - (lam3 + lam4 - lam5)*sab)*vev, 0}},

C[ S[2] , S[2] , S[2] ] == {{(-3*I)*(cab^3*lam7 - cab^2*(lam3 + lam4 + lam5)*sab + 3*cab*lam6*sab^2 - lam1*sab^3)*vev, 0}},

C[ S[7] , -S[7] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[5] , -S[5] , V[1] , V[1] ] == {{2*EL^2*(cphi + I*sphi)*(I*cphi + sphi), 0}},

C[ S[4] , -S[4] , V[1] , V[1] ] == {{2*EL^2*(cphi + I*sphi)*(I*cphi + sphi), 0}},

C[ S[7] , -S[7] , V[1] ] == {{(-I)*gc171, 0}, {I*gc171, 0}},

C[ S[5] , -S[5] , V[1] ] == {{(-I)*gc172, 0}, {I*gc172, 0}},

C[ S[4] , -S[4] , V[1] ] == {{(-I)*gc173, 0}, {I*gc173, 0}},

C[ S[6] , -S[7] , V[1] , V[3] ] == {{-EL^2/(2*sw), 0}},

C[ -S[7] , S[1] , V[1] , V[3] ] == {{((I/2)*cab*EL^2)/sw, 0}},

C[ S[3] , -S[4] , V[1] , V[3] ] == {{-(cphi*EL^2)/(2*sw), 0}},

C[ S[2] , -S[4] , V[1] , V[3] ] == {{((I/2)*cab*cphi*EL^2)/sw, 0}},

C[ -S[7] , S[2] , V[1] , V[3] ] == {{((-I/2)*EL^2*sab)/sw, 0}},

C[ S[1] , -S[4] , V[1] , V[3] ] == {{((I/2)*cphi*EL^2*sab)/sw, 0}},

C[ S[3] , -S[5] , V[1] , V[3] ] == {{-(EL^2*sphi)/(2*sw), 0}},

C[ S[2] , -S[5] , V[1] , V[3] ] == {{((I/2)*cab*EL^2*sphi)/sw, 0}},

C[ S[1] , -S[5] , V[1] , V[3] ] == {{((I/2)*EL^2*sab*sphi)/sw, 0}},

C[ -S[7] , V[1] , V[3] ] == {{((I/2)*EL^2*vev)/sw, 0}},

C[ S[6] , -S[7] , V[3] ] == {{-gc184, 0}, {gc184, 0}},

C[ -S[7] , S[1] , V[3] ] == {{(-I)*gc185, 0}, {I*gc185, 0}},

C[ -S[7] , S[2] , V[3] ] == {{(-I)*gc186, 0}, {I*gc186, 0}},

C[ S[3] , -S[4] , V[3] ] == {{-gc187, 0}, {gc187, 0}},

C[ S[3] , -S[5] , V[3] ] == {{-gc188, 0}, {gc188, 0}},

C[ S[2] , -S[4] , V[3] ] == {{(-I)*gc189, 0}, {I*gc189, 0}},

C[ S[2] , -S[5] , V[3] ] == {{(-I)*gc190, 0}, {I*gc190, 0}},

C[ S[1] , -S[4] , V[3] ] == {{(-I)*gc191, 0}, {I*gc191, 0}},

C[ S[1] , -S[5] , V[3] ] == {{(-I)*gc192, 0}, {I*gc192, 0}},

C[ S[6] , S[7] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[7] , S[1] , V[1] , -V[3] ] == {{((I/2)*cab*EL^2)/sw, 0}},

C[ S[3] , S[4] , V[1] , -V[3] ] == {{(cphi*EL^2)/(2*sw), 0}},

C[ S[2] , S[4] , V[1] , -V[3] ] == {{((I/2)*cab*cphi*EL^2)/sw, 0}},

C[ S[7] , S[2] , V[1] , -V[3] ] == {{((-I/2)*EL^2*sab)/sw, 0}},

C[ S[1] , S[4] , V[1] , -V[3] ] == {{((I/2)*cphi*EL^2*sab)/sw, 0}},

C[ S[3] , S[5] , V[1] , -V[3] ] == {{(EL^2*sphi)/(2*sw), 0}},

C[ S[2] , S[5] , V[1] , -V[3] ] == {{((I/2)*cab*EL^2*sphi)/sw, 0}},

C[ S[1] , S[5] , V[1] , -V[3] ] == {{((I/2)*EL^2*sab*sphi)/sw, 0}},

C[ S[7] , V[1] , -V[3] ] == {{((I/2)*EL^2*vev)/sw, 0}},

C[ S[6] , S[7] , -V[3] ] == {{-gc203, 0}, {gc203, 0}},

C[ S[7] , S[1] , -V[3] ] == {{(-I)*gc204, 0}, {I*gc204, 0}},

C[ S[7] , S[2] , -V[3] ] == {{(-I)*gc205, 0}, {I*gc205, 0}},

C[ S[3] , S[4] , -V[3] ] == {{-gc206, 0}, {gc206, 0}},

C[ S[3] , S[5] , -V[3] ] == {{-gc207, 0}, {gc207, 0}},

C[ S[2] , S[4] , -V[3] ] == {{(-I)*gc208, 0}, {I*gc208, 0}},

C[ S[2] , S[5] , -V[3] ] == {{(-I)*gc209, 0}, {I*gc209, 0}},

C[ S[1] , S[4] , -V[3] ] == {{(-I)*gc210, 0}, {I*gc210, 0}},

C[ S[1] , S[5] , -V[3] ] == {{(-I)*gc211, 0}, {I*gc211, 0}},

C[ S[6] , S[6] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[7] , -S[7] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cab^2 + sab^2))/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cab^2 + sab^2))/sw^2, 0}},

C[ S[4] , -S[4] , V[3] , -V[3] ] == {{((I/2)*cphi^2*EL^2)/sw^2, 0}},

C[ -S[5] , S[4] , V[3] , -V[3] ] == {{((I/2)*cphi*EL^2*sphi)/sw^2, 0}},

C[ S[5] , -S[4] , V[3] , -V[3] ] == {{((I/2)*cphi*EL^2*sphi)/sw^2, 0}},

C[ S[5] , -S[5] , V[3] , -V[3] ] == {{((I/2)*EL^2*sphi^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*cab*EL^2*vev)/sw^2, 0}},

C[ S[2] , V[3] , -V[3] ] == {{((-I/2)*EL^2*sab*vev)/sw^2, 0}},

C[ S[7] , -S[7] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[4] , -S[4] , V[1] , V[2] ] == {{(I*EL^2*(-2*sphi^2*sw^2 + cphi^2*(cw^2 - sw^2)))/(cw*sw), 0}},

C[ -S[5] , S[4] , V[1] , V[2] ] == {{(I*cphi*EL^2*sphi*(cw^2 + sw^2))/(cw*sw), 0}},

C[ S[5] , -S[4] , V[1] , V[2] ] == {{(I*cphi*EL^2*sphi*(cw^2 + sw^2))/(cw*sw), 0}},

C[ S[5] , -S[5] , V[1] , V[2] ] == {{(I*EL^2*(cw^2*sphi^2 - (2*cphi^2 + sphi^2)*sw^2))/(cw*sw), 0}},

C[ S[6] , S[1] , V[2] ] == {{-gc228, 0}, {gc228, 0}},

C[ S[6] , S[2] , V[2] ] == {{-gc229, 0}, {gc229, 0}},

C[ S[7] , -S[7] , V[2] ] == {{(-I)*gc230, 0}, {I*gc230, 0}},

C[ S[3] , S[2] , V[2] ] == {{-gc231, 0}, {gc231, 0}},

C[ S[3] , S[1] , V[2] ] == {{-gc232, 0}, {gc232, 0}},

C[ S[5] , -S[4] , V[2] ] == {{(-I)*gc233, 0}, {I*gc233, 0}},

C[ S[5] , -S[5] , V[2] ] == {{I*gc234*(cw^2*sphi^2 - (2*cphi^2 + sphi^2)*sw^2), 0}, {(-I)*gc234*(cw^2*sphi^2 - (2*cphi^2 + sphi^2)*sw^2), 0}},

C[ -S[5] , S[4] , V[2] ] == {{(-I)*gc235, 0}, {I*gc235, 0}},

C[ S[4] , -S[4] , V[2] ] == {{(-I)*gc236, 0}, {I*gc236, 0}},

C[ S[6] , -S[7] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ -S[7] , S[1] , V[3] , V[2] ] == {{((-I/2)*cab*EL^2)/cw, 0}},

C[ S[3] , -S[4] , V[3] , V[2] ] == {{(cphi*EL^2)/(2*cw), 0}},

C[ S[2] , -S[4] , V[3] , V[2] ] == {{((-I/2)*cab*cphi*EL^2)/cw, 0}},

C[ -S[7] , S[2] , V[3] , V[2] ] == {{((I/2)*EL^2*sab)/cw, 0}},

C[ S[1] , -S[4] , V[3] , V[2] ] == {{((-I/2)*cphi*EL^2*sab)/cw, 0}},

C[ S[3] , -S[5] , V[3] , V[2] ] == {{(EL^2*sphi)/(2*cw), 0}},

C[ S[2] , -S[5] , V[3] , V[2] ] == {{((-I/2)*cab*EL^2*sphi)/cw, 0}},

C[ S[1] , -S[5] , V[3] , V[2] ] == {{((-I/2)*EL^2*sab*sphi)/cw, 0}},

C[ -S[7] , V[3] , V[2] ] == {{((-I/2)*EL^2*vev)/cw, 0}},

C[ S[6] , S[7] , -V[3] , V[2] ] == {{-EL^2/(2*cw), 0}},

C[ S[7] , S[1] , -V[3] , V[2] ] == {{((-I/2)*cab*EL^2)/cw, 0}},

C[ S[3] , S[4] , -V[3] , V[2] ] == {{-(cphi*EL^2)/(2*cw), 0}},

C[ S[2] , S[4] , -V[3] , V[2] ] == {{((-I/2)*cab*cphi*EL^2)/cw, 0}},

C[ S[7] , S[2] , -V[3] , V[2] ] == {{((I/2)*EL^2*sab)/cw, 0}},

C[ S[1] , S[4] , -V[3] , V[2] ] == {{((-I/2)*cphi*EL^2*sab)/cw, 0}},

C[ S[3] , S[5] , -V[3] , V[2] ] == {{-(EL^2*sphi)/(2*cw), 0}},

C[ S[2] , S[5] , -V[3] , V[2] ] == {{((-I/2)*cab*EL^2*sphi)/cw, 0}},

C[ S[1] , S[5] , -V[3] , V[2] ] == {{((-I/2)*EL^2*sab*sphi)/cw, 0}},

C[ S[7] , -V[3] , V[2] ] == {{((-I/2)*EL^2*vev)/cw, 0}},

C[ S[6] , S[6] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[7] , -S[7] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[3] , S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cab^2 + sab^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cab^2 + sab^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[4] , -S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*(4*sphi^2*sw^4 + cphi^2*(cw^2 - sw^2)^2))/(cw^2*sw^2), 0}},

C[ -S[5] , S[4] , V[2] , V[2] ] == {{((I/2)*cphi*EL^2*sphi*(cw^2 - 3*sw^2)*(cw^2 + sw^2))/(cw^2*sw^2), 0}},

C[ S[5] , -S[4] , V[2] , V[2] ] == {{((I/2)*cphi*EL^2*sphi*(cw^2 - 3*sw^2)*(cw^2 + sw^2))/(cw^2*sw^2), 0}},

C[ S[5] , -S[5] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^4*sphi^2 - 2*cw^2*sphi^2*sw^2 + (4*cphi^2 + sphi^2)*sw^4))/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*cab*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[2] , V[2] , V[2] ] == {{((-I/2)*EL^2*sab*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc268*IndexDelta[e1x2, e2x2], 0}, {I*gc268*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc269*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc269*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc270*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc270*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc271*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc271*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc272*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc272*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc273[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc274[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc275*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc276*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc277L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc277R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc278L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc278R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc279*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc280L*IndexDelta[e1x2, e2x2], 0}, {I*gc280R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[7] ] == {{I*gc281L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc281R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[6] ] == {{gc282L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc282R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc283L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc283R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[2] ] == {{I*gc284L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc284R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[7] ] == {{I*gc285[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[6] ] == {{gc286L[e1x2, e2x2], 0}, {gc286R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc287L[e1x2, e2x2], 0}, {I*gc287R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[2] ] == {{I*gc288L[e1x2, e2x2], 0}, {I*gc288R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[4] ] == {{I*gc289[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[5] ] == {{I*gc290[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[3] ] == {{gc291L[e1x2, e2x2], 0}, {gc291R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[7] ] == {{I*gc292L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc292R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[6] ] == {{gc293L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc293R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc294L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc294R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[2] ] == {{I*gc295L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc295R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[7] ] == {{0, 0}, {I*gc296R[e1x2, e2x2], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[4] ] == {{0, 0}, {I*gc297R[e1x2, e2x2], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[5] ] == {{0, 0}, {I*gc298R[e1x2, e2x2], 0}},

C[ -F[1, {e1x2}] , -F[2, {e2x2}] , -S[5] ] == {{0, 0}, {I*gc299R[e1x2, e2x2], 0}},

C[ -F[1, {e1x2}] , -F[2, {e2x2}] , -S[4] ] == {{0, 0}, {I*gc300R[e1x2, e2x2], 0}},

C[ F[2, {e1x2}] , F[1, {e2x2}] , S[5] ] == {{I*gc301[e1x2, e2x2], 0}, {0, 0}},

C[ F[2, {e1x2}] , F[1, {e2x2}] , S[4] ] == {{I*gc302[e1x2, e2x2], 0}, {0, 0}},

C[ -U[1] , U[32] , V[3] ] == {{I*gc303, 0}, {I*gc303, 0}, {0, 0}},

C[ -U[1] , U[31] , -V[3] ] == {{I*gc304, 0}, {I*gc304, 0}, {0, 0}},

C[ -S[7] , -U[32] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[32] , U[1] , -V[3] ] == {{I*gc306, 0}, {I*gc306, 0}, {0, 0}},

C[ -U[32] , U[32] , V[1] ] == {{I*gc307, 0}, {I*gc307, 0}, {0, 0}},

C[ -U[32] , U[32] , V[2] ] == {{I*gc308, 0}, {I*gc308, 0}, {0, 0}},

C[ -S[7] , -U[32] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[32] , U[2] , -V[3] ] == {{I*gc310, 0}, {I*gc310, 0}, {0, 0}},

C[ S[7] , -U[31] , U[1] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ -U[31] , U[1] , V[3] ] == {{I*gc312, 0}, {I*gc312, 0}, {0, 0}},

C[ -U[31] , U[31] , V[1] ] == {{I*gc313, 0}, {I*gc313, 0}, {0, 0}},

C[ -U[31] , U[31] , V[2] ] == {{I*gc314, 0}, {I*gc314, 0}, {0, 0}},

C[ S[7] , -U[31] , U[2] ] == {{-(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[31] , U[2] , V[3] ] == {{I*gc316, 0}, {I*gc316, 0}, {0, 0}},

C[ S[7] , -U[2] , U[32] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[32] , V[3] ] == {{I*gc318, 0}, {I*gc318, 0}, {0, 0}},

C[ -S[7] , -U[2] , U[31] ] == {{-(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[31] , -V[3] ] == {{I*gc320, 0}, {I*gc320, 0}, {0, 0}},

C[ -U[4, {e1x1}] , U[4, {e2x1}] , V[4, {e3x2}] ] == {{gc321*SUNF[e3x2, e1x1, e2x1], 0}, {gc321*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -GS,
     gc2 -> -GS^2,
     gc3 -> EL,
     gc4 -> -EL^2,
     gc5 -> (cw*EL)/sw,
     gc6 -> EL^2/sw^2,
     gc7 -> (cw*EL^2)/sw,
     gc8 -> -((cw^2*EL^2)/sw^2),
     gc171 -> -EL,
     gc172 -> -(EL*(cphi^2 + sphi^2)),
     gc173 -> -(EL*(cphi^2 + sphi^2)),
     gc184 -> EL/(2*sw),
     gc185 -> (cab*EL)/(2*sw),
     gc186 -> -(EL*sab)/(2*sw),
     gc187 -> (cphi*EL)/(2*sw),
     gc188 -> (EL*sphi)/(2*sw),
     gc189 -> -(cab*cphi*EL)/(2*sw),
     gc190 -> -(cab*EL*sphi)/(2*sw),
     gc191 -> -(cphi*EL*sab)/(2*sw),
     gc192 -> -(EL*sab*sphi)/(2*sw),
     gc203 -> EL/(2*sw),
     gc204 -> -(cab*EL)/(2*sw),
     gc205 -> (EL*sab)/(2*sw),
     gc206 -> (cphi*EL)/(2*sw),
     gc207 -> (EL*sphi)/(2*sw),
     gc208 -> (cab*cphi*EL)/(2*sw),
     gc209 -> (cab*EL*sphi)/(2*sw),
     gc210 -> (cphi*EL*sab)/(2*sw),
     gc211 -> (EL*sab*sphi)/(2*sw),
     gc228 -> -(cab*EL*(cw^2 + sw^2))/(2*cw*sw),
     gc229 -> (EL*sab*(cw^2 + sw^2))/(2*cw*sw),
     gc230 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc231 -> -(cab*EL*(cw^2 + sw^2))/(2*cw*sw),
     gc232 -> -(EL*sab*(cw^2 + sw^2))/(2*cw*sw),
     gc233 -> -(cphi*EL*sphi*(cw^2 + sw^2))/(2*cw*sw),
     gc234 -> EL/(2*cw*sw),
     gc235 -> (cphi*EL*sphi*(cw^2 + sw^2))/(2*cw*sw),
     gc236 -> (EL*(2*sphi^2*sw^2 + cphi^2*(-cw^2 + sw^2)))/(2*cw*sw),
     gc268 -> -EL,
     gc269 -> (2*EL)/3,
     gc270 -> -EL/3,
     gc271 -> GS,
     gc272 -> GS,
     gc273[e1x2_, e2x2_] -> (EL*CKM[e1x2, e2x2])/(Sqrt[2]*sw),
     gc274[e1x2_, e2x2_] -> (EL*Conjugate[CKM[e2x2, e1x2]])/(Sqrt[2]*sw),
     gc275 -> EL/(Sqrt[2]*sw),
     gc276 -> EL/(Sqrt[2]*sw),
     gc277L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc277R -> (-2*EL*sw)/(3*cw),
     gc278L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc278R -> (EL*sw)/(3*cw),
     gc279 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc280L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc280R -> (EL*sw)/cw,
     gc281L[e1x2_, e2x2_] -> -IndexSum[Conjugate[CKM[e2x2, Generation$1]]*Conjugate[yd[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc281R[e1x2_, e2x2_] -> IndexSum[Conjugate[CKM[Generation$1, e1x2]]*yu[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc282L[e1x2_, e2x2_] -> -(Conjugate[yd[e2x2, e1x2]]/Sqrt[2]),
     gc282R[e1x2_, e2x2_] -> yd[e1x2, e2x2]/Sqrt[2],
     gc283L[e1x2_, e2x2_] -> -((cab*Conjugate[yd[e2x2, e1x2]])/Sqrt[2]),
     gc283R[e1x2_, e2x2_] -> -((cab*yd[e1x2, e2x2])/Sqrt[2]),
     gc284L[e1x2_, e2x2_] -> (sab*Conjugate[yd[e2x2, e1x2]])/Sqrt[2],
     gc284R[e1x2_, e2x2_] -> (sab*yd[e1x2, e2x2])/Sqrt[2],
     gc285[e1x2_, e2x2_] -> -Conjugate[yl[e2x2, e1x2]],
     gc286L[e1x2_, e2x2_] -> -(Conjugate[yl[e2x2, e1x2]]/Sqrt[2]),
     gc286R[e1x2_, e2x2_] -> yl[e1x2, e2x2]/Sqrt[2],
     gc287L[e1x2_, e2x2_] -> (-(cab*Conjugate[yl[e2x2, e1x2]]) - sab*Conjugate[ylz[e2x2, e1x2]])/Sqrt[2],
     gc287R[e1x2_, e2x2_] -> (-(cab*yl[e1x2, e2x2]) - sab*ylz[e1x2, e2x2])/Sqrt[2],
     gc288L[e1x2_, e2x2_] -> (sab*Conjugate[yl[e2x2, e1x2]] - cab*Conjugate[ylz[e2x2, e1x2]])/Sqrt[2],
     gc288R[e1x2_, e2x2_] -> (sab*yl[e1x2, e2x2] - cab*ylz[e1x2, e2x2])/Sqrt[2],
     gc289[e1x2_, e2x2_] -> -(cphi*Conjugate[ylz[e2x2, e1x2]]),
     gc290[e1x2_, e2x2_] -> -(sphi*Conjugate[ylz[e2x2, e1x2]]),
     gc291L[e1x2_, e2x2_] -> -(Conjugate[ylz[e2x2, e1x2]]/Sqrt[2]),
     gc291R[e1x2_, e2x2_] -> ylz[e1x2, e2x2]/Sqrt[2],
     gc292L[e1x2_, e2x2_] -> IndexSum[CKM[Generation$1, e2x2]*Conjugate[yu[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc292R[e1x2_, e2x2_] -> -IndexSum[CKM[e1x2, Generation$1]*yd[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc293L[e1x2_, e2x2_] -> Conjugate[yu[e2x2, e1x2]]/Sqrt[2],
     gc293R[e1x2_, e2x2_] -> -(yu[e1x2, e2x2]/Sqrt[2]),
     gc294L[e1x2_, e2x2_] -> -((cab*Conjugate[yu[e2x2, e1x2]])/Sqrt[2]),
     gc294R[e1x2_, e2x2_] -> -((cab*yu[e1x2, e2x2])/Sqrt[2]),
     gc295L[e1x2_, e2x2_] -> (sab*Conjugate[yu[e2x2, e1x2]])/Sqrt[2],
     gc295R[e1x2_, e2x2_] -> (sab*yu[e1x2, e2x2])/Sqrt[2],
     gc296R[e1x2_, e2x2_] -> -yl[e1x2, e2x2],
     gc297R[e1x2_, e2x2_] -> -(cphi*ylz[e1x2, e2x2]),
     gc298R[e1x2_, e2x2_] -> -(sphi*ylz[e1x2, e2x2]),
     gc299R[e1x2_, e2x2_] -> -(cphi*(Conjugate[fl[e1x2, e2x2]] - Conjugate[fl[e2x2, e1x2]])),
     gc300R[e1x2_, e2x2_] -> sphi*(Conjugate[fl[e1x2, e2x2]] - Conjugate[fl[e2x2, e1x2]]),
     gc301[e1x2_, e2x2_] -> cphi*(fl[e1x2, e2x2] - fl[e2x2, e1x2]),
     gc302[e1x2_, e2x2_] -> -(sphi*(fl[e1x2, e2x2] - fl[e2x2, e1x2])),
     gc303 -> EL,
     gc304 -> -EL,
     gc306 -> EL,
     gc307 -> -EL,
     gc308 -> -((cw*EL)/sw),
     gc310 -> (cw*EL)/sw,
     gc312 -> -EL,
     gc313 -> EL,
     gc314 -> (cw*EL)/sw,
     gc316 -> -((cw*EL)/sw),
     gc318 -> (cw*EL)/sw,
     gc320 -> -((cw*EL)/sw),
     gc321 -> GS};

